name: MSVC Development Environment
author: Michael Beckh
description: Set environment variables for a MSVC development environment.
inputs:
  triplet:
    description: The root build directory (optional, defaults to x64-windows-static)
    default: x64-windows-static
runs:
  using: composite
  steps:
    - name: Configure Development Environment
      shell: cmd
      working-directory: ${{github.action_path}}
      run: |
        set VCPKG_KEEP_ENV_VARS=PATH;Path
        set > old.env
        %VCPKG_INSTALLATION_ROOT%\vcpkg.exe env set --overlay-triplets=${{github.action_path}}\modules\triplets --triplet ${{inputs.triplet}} > new.env
    - name: Detect Changes to Development Environment
      shell: bash
      working-directory: ${{github.action_path}}
      # new.env may contain multiple entries for PATH with different case (https://github.com/microsoft/vcpkg-tool/pull/840)
      run: |
        join -v 2 -t '' -i <(sort -f old.env) <(awk 'BEGIN{FS="="}!seen[toupper($1)]++' new.env | sort -f) > dev.env
        grep -v -i ^PATH= dev.env >> $GITHUB_ENV
        p=$(grep -i ^PATH= dev.env | cut -d = -f 2- | awk 'BEGIN{RS=FS="[;\n]";ORS=";"}!seen[tolower($0)]++')
        n=$(grep -o -i ^PATH= dev.env)
        echo $n${p%;} >> $GITHUB_ENV
        echo VCPKG_KEEP_ENV_VARS=${n%=} >> $GITHUB_ENV
        echo "::group::Modified Environment Variables"
        cut -d = -f 1 dev.env
        echo "::endgroup::"
