name: MSVC Development Environment
author: Michael Beckh
description: Set environment variables for a MSVC development environment.
inputs:
  triplet:
    description: The root build directory (optional, defaults to x64-windows-static)
    default: x64-windows-static
runs:
  using: composite
  steps:
    - name: Configure Development Environment
      shell: cmd
      working-directory: ${{github.action_path}}
      run: |
        set VCPKG_KEEP_ENV_VARS=PATH;Path
        set > old.env
        %VCPKG_INSTALLATION_ROOT%\vcpkg.exe env set --overlay-triplets=${{github.action_path}}\modules\triplets --triplet ${{inputs.triplet}} > new.env
    - name: Detect Changes to Development Environment
      shell: bash
      working-directory: ${{github.action_path}}
      # new.env may contain multiple entries for PATH with different case
      run: |
        echo "::group::Debug old.env"
        sort -t = -k 1,1 old.env
        echo "::endgroup::"
        echo "::group::Debug new.env"
        awk 'BEGIN{FS="="}!seen[toupper($1)]' new.env | sort -f -t = -k 1,1
        echo "::endgroup::"
        join -i -j 1 -t = -v 2 <(sort -f -t = -k 1,1 old.env) <(awk 'BEGIN{FS="="}!seen[toupper($1)]' new.env | sort -f -t = -k 1,1) > dev.env
        echo "::group::Debug dev.env"
        cat dev.env
        echo "::endgroup::"
        grep -v ^PATH= dev.env >> $GITHUB_ENV
        p=$(grep ^PATH= dev.env | cut -d = -f 2- | awk 'BEGIN{RS=FS="[;\n]";ORS=";"}!seen[tolower($0)]')
        echo PATH=${p%;} >> $GITHUB_ENV
        echo VCPKG_KEEP_ENV_VARS=PATH >> $GITHUB_ENV
        echo "::group::Modified Environment Variables"
        cut -d = -f 1 dev.env
        echo "::endgroup::"
