name: MSVC Development Environment
author: Michael Beckh
description: Set environment variables for a MSVC development environment.
inputs:
  triplet:
    description: The root build directory (optional, defaults to x64-windows-static)
    default: x64-windows-static
runs:
  using: composite
  steps:
    - name: Configure Development Environment
      shell: cmd
      working-directory: ${{github.action_path}}
      run: |
        set > old.env
        set VCPKG_KEEP_ENV_VARS=PATH
        %VCPKG_INSTALLATION_ROOT%\vcpkg.exe env set --overlay-triplets=${{github.action_path}}\modules\triplets --triplet ${{inputs.triplet}} > new.env
    - name: Detect Changes to Development Environment
      shell: bash
      working-directory: ${{github.action_path}}
      run: |
        join -v 2 <(sort -t = old.env) <(sort -t = new.env) > dev.env
        grep -v ^PATH= dev.env >> $GITHUB_ENV
        p=$(grep ^PATH= dev.env | cut -d = -f 2- | awk 'BEGIN{RS=FS="[;\n]";ORS=";"}!seen[tolower($0)]')
        echo PATH=${p%;} >> $GITHUB_ENV
