name: MSVC Development Environment
author: Michael Beckh
description: Set environment variables for a MSVC development environment.
inputs:
  arch:
    description: The architecture (optional, defaults to amd64 aka x64)
    default: amd64
runs:
  using: composite
  steps:
    - name: Configure Development Environment
      shell: cmd
      working-directory: ${{github.action_path}}
      env:
        INPUT_ARCH: ${{inputs.arch == 'x64' && 'amd64' || inputs.arch}}
      run: |
        rem Configure Development Environment
        for /f "usebackq delims=<" %%p in (`vswhere -latest -property installationPath -format value`) do set CMU_VS_ROOT=%%p
        set > old.env
        echo ::group::Running "%CMU_VS_ROOT%\VC\Auxiliary\Build\vcvarsall.bat" %INPUT_ARCH%
        call "%CMU_VS_ROOT%\VC\Auxiliary\Build\vcvarsall.bat" %INPUT_ARCH%
        echo ::endgroup::
        set > new.env

    - name: Detect Changes to Development Environment
      shell: bash
      working-directory: ${{github.action_path}}
      run: |
        # Detect Changes to Development Environment
        special='(EXTERNAL_)?INCLUDE|LIB(PATH)?|PATH'
        join -v 2 -t '' -i <(sort -f old.env) <(sort -f new.env) | \
        tee >(egrep -v -i "^($special)=" > dev.env) | \
        egrep -i "^($special)=" | while read -r line; do
          value=$(awk 'BEGIN{RS=FS="[;\n]";ORS=";"}!seen[tolower($0)]++' <<< ${line#*=})
          echo ${line%%=*}=${value%;}
        done >> dev.env
        
        echo "::group::Environment Variables for Development Environment"
        tee -a $GITHUB_ENV < dev.env
        echo "::endgroup::"
