name: Configure
author: Michael Beckh
description: Configure a project using CMake and cmake-utils.
inputs:
  build-root:
    description: The root build directory (optional, defaults to github.workspace)
    default: .
  preset:
    description: Use the specified CMake configure preset (optional)
  source-dir:
    description: The CMake source directory (optional, defaults to github.workspace if no preset is used)
  binary-dir:
    description: The CMake binary directory (optional, defaults to github.workspace if no preset is used)
  generator:
    description: The CMake generator (optional, defaults to Ninja if no preset is used)
  configuration:
    description: The CMake build type for CMAKE_BUILD_TYPE (optional, defaults to Release if no preset is used and generator is Ninja)
  configurations:
    description: The CMake configuration types for CMAKE_CONFIGURATION_TYPES (optional, defaults to Debug;Release if no preset is used and generator is Ninja Multi-Config)
  extra-args:
    description: Additional arguments for CMake (optional)
runs:
  using: composite
  steps:
    - name: Configure NuGet
      shell: cmd
      run: |
        nuget sources Add -Source "https://nuget.pkg.github.com/${{format('{0}', github.repository_owner)}}/index.json" -StorePasswordInClearText -Name "GitHub" -UserName "${{format('{0}', github.repository_owner)}}" -Password "${{github.token}}" -NonInteractive
        nuget setapikey "${{github.token}}" -Source "https://nuget.pkg.github.com/${{format('{0}', github.repository_owner)}}/index.json" -NonInteractive
    - name: Configure Build
      shell: cmd
      run: |
        cmake -DBUILD_ROOT:PATH="${{format('{0}/{1}', github.workspace, inputs.build-root)}}" -DCMAKE_TOOLCHAIN_FILE:FILEPATH="${{github.action_path}}/../Toolchain.cmake" -Dvcpkg_ROOT:FILEPATH="%VCPKG_INSTALLATION_ROOT%" -DVCPKG_BINARY_SOURCES:STRING=clear;nuget,GitHub,readwrite ^
          ${{inputs.preset && format('--preset "{0}"', inputs.preset) || ''}} ^
          ${{(inputs.generator || !inputs.preset) && format('-G "{0}"', inputs.generator || 'Ninja') || ''}} ^
          ${{(inputs.configuration || !inputs.preset && (inputs.generator == 'Ninja' || !inputs.generator)) && format('-DCMAKE_BUILD_TYPE:STRING={0}', inputs.configuration || 'Release') || ''}} ^
          ${{(inputs.configurations || !inputs.preset && inputs.generator == 'Ninja Multi-Config') && format('-DCMAKE_CONFIGURATION_TYPES:STRING={0}', inputs.configurations || 'Debug;Release') || ''}} ^
          ${{(inputs.source-dir || !inputs.preset) && format('-S "{0}"', inputs.source-dir || '.') || ''}} ^
          ${{(inputs.binary-dir || !inputs.preset) && format('-B "{0}"', inputs.binary-dir || '.') || ''}} ^
          ${{format('{0}', inputs.extra-args)}}
