name: Configure
author: Michael Beckh
description: Configure a project using CMake and cmake-utils.
inputs:
  build-root:
    description: The root build directory (optional, defaults to github.workspace)
    default: .
  preset:
    description: Use the specified CMake configure preset (optional)
  source-dir:
    description: The CMake source directory (optional, defaults to github.workspace if no preset is used)
  binary-dir:
    description: The CMake binary directory (optional, defaults to github.workspace if no preset is used)
  generator:
    description: The CMake generator (optional, defaults to Ninja if no preset is used)
  configuration:
    description: The CMake build type for CMAKE_BUILD_TYPE (optional, defaults to Release if no preset is used and generator is Ninja)
  configurations:
    description: The CMake configuration types for CMAKE_CONFIGURATION_TYPES (optional, defaults to Debug;Release if no preset is used and generator is Ninja Multi-Config)
  extra-args:
    description: Additional arguments for CMake (optional)
runs:
  using: composite
  steps:
    - name: Configure NuGet
      shell: cmd
      env:
        GITHUB_TOKEN: ${{github.token}}
      run: |
        rem Configure NuGet
        nuget sources Add -Name "GitHub" -Source "https://nuget.pkg.github.com/%GITHUB_REPOSITORY_OWNER%/index.json" -UserName "%GITHUB_REPOSITORY_OWNER%" -Password "%GITHUB_TOKEN%" -StorePasswordInClearText -NonInteractive
        nuget setapikey "%GITHUB_TOKEN%" -Source "https://nuget.pkg.github.com/%GITHUB_REPOSITORY_OWNER%/index.json" -NonInteractive
    - name: Configure Build
      shell: cmd
      env:
        INPUT_BUILD_ROOT: ${{inputs.build-root}}
        INPUT_PRESET: ${{inputs.preset}}
        INPUT_GENERATOR: ${{(inputs.generator || !inputs.preset) && (inputs.generator || 'Ninja') || ''}}
        INPUT_CONFIGURATION: ${{((inputs.configuration || !inputs.preset) && (inputs.generator == 'Ninja' || !inputs.generator)) && (inputs.configuration || 'Release') || ''}}
        INPUT_CONFIGURATIONS: ${{(inputs.configurations || !inputs.preset && inputs.generator == 'Ninja Multi-Config') && (inputs.configurations || 'Debug;Release') || ''}}
        INPUT_SOURCE_DIR: ${{(inputs.source-dir || !inputs.preset) && (inputs.source-dir || '.') || ''}}
        INPUT_BINARY_DIR: ${{(inputs.binary-dir || !inputs.preset) && (inputs.binary-dir || '.') || ''}}
        INPUT_EXTRA_ARGS: ${{inputs.extra-args}}
      run: |
        rem Configure Build
        cmake ${{env.INPUT_PRESET && '--preset "%INPUT_PRESET%"' || ''}} -DBUILD_ROOT:PATH="%GITHUB_WORKSPACE%/%INPUT_BUILD_ROOT%" -DCMAKE_TOOLCHAIN_FILE:FILEPATH="%GITHUB_ACTION_PATH%/../Toolchain.cmake" ^
          -Dvcpkg_ROOT:FILEPATH="%VCPKG_INSTALLATION_ROOT%" -DVCPKG_BINARY_SOURCES:STRING=clear;nuget,GitHub,readwrite ^
          ${{env.INPUT_GENERATOR && '-G "%INPUT_GENERATOR%"' || ''}} ^
          ${{env.INPUT_CONFIGURATION && '-DCMAKE_BUILD_TYPE:STRING="%INPUT_CONFIGURATION%"' || ''}} ${{env.INPUT_CONFIGURATIONS && '-DCMAKE_CONFIGURATION_TYPES:STRING="%INPUT_CONFIGURATIONS%"' || ''}} ^
          ${{env.INPUT_SOURCE_DIR && '-S "%INPUT_SOURCE_DIR%"' || ''}} ${{env.INPUT_BINARY_DIR && '-B "%INPUT_BINARY_DIR%"' || ''}} ^
          %INPUT_EXTRA_ARGS%
