name: Bug
on:
  push:
permissions: write-all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      env:
        GITHUB_TOKEN: ${{github.token}}
      run: |
        curl \
          -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" \
          "$GITHUB_API_URL/repos/mbeckh/vcpkg-registry/actions/workflows/clean_packages.yml"
