name: build

on:
  push:
    branches: [ master, 'feature**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    runs-on: windows-latest
    strategy:
      matrix:
        # Release
        configuration: [ Debug ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create Build Directory
      run: cmake -E make_directory ${{github.workspace}}/build/project/${{ matrix.configuration }}

    - name: Configure
      working-directory: ${{github.workspace}}/build/project/${{ matrix.configuration }}
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DBUILD_ROOT=${{github.workspace}}/build -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/toolchain.cmake -G Ninja ${{github.workspace}}/test

    - name: Test
      working-directory: ${{github.workspace}}/build/project/${{ matrix.configuration }}
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        ctest -C ${{ matrix.configuration }}
