name: build

on:
  push:
    branches: [ master, 'feature**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    runs-on: windows-latest
    strategy:
      matrix:
        # Release
        configuration: [ Debug ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: source

    - name: Create Build Directory
      shell: bash
      run: |
        GITHUB_REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}
        echo GITHUB_REPOSITORY_NAME=${GITHUB_REPOSITORY_NAME} >> $GITHUB_ENV
        cmake -E make_directory ${{github.workspace}}/build/$GITHUB_REPOSITORY_NAME/${{matrix.configuration}}

    - name: Cache vcpkg
      uses: actions/cache@v2
      with:
        path: |
          ${{github.workspace}}/build/${{env.GITHUB_REPOSITORY_NAME}}/${{matrix.configuration}}/vcpkg_installed
          ${{github.workspace}}/build/${{env.GITHUB_REPOSITORY_NAME}}/vcpkg-packages
        key: vcpkg-${{hashFiles('source/**/vcpkg.json')}}

    - name: Configure
      shell: cmd
      working-directory: ${{github.workspace}}\build\${{env.GITHUB_REPOSITORY_NAME}}\${{matrix.configuration}}
      run: |
        echo "Running in ${{github.workspace}}/build/${{env.GITHUB_REPOSITORY_NAME}}/${{matrix.configuration}}"
        nuget sources add -source "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json" -storepasswordincleartext -name "GitHub" -username "${{github.repository_owner}}" -password "${{secrets.GITHUB_TOKEN}}"
        echo "Running build"
        cmake -DCMAKE_BUILD_TYPE=${{matrix.configuration}} -DBUILD_ROOT=${{github.workspace}}/build -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/source/Toolchain.cmake -Dvcpkg_ROOT=%VCPKG_INSTALLATION_ROOT% -DVCPKG_BINARY_SOURCES=clear;nuget,GitHub,readwrite -G Ninja ${{github.workspace}}/source/test

    - name: Build
      shell: cmd
      working-directory: ${{github.workspace}}/build/${{env.GITHUB_REPOSITORY_NAME}}/${{matrix.configuration}}
      run: cmake --build .

    - name: Test
      if: matrix.configuration != 'Debug'
      shell: cmd
      working-directory: ${{github.workspace}}/build/${{env.GITHUB_REPOSITORY_NAME}}/${{matrix.configuration}}
      run: ctest -C ${{matrix.configuration}} --output-on-failure

    - name: Coverage (TODO)
      if: matrix.configuration == 'Debug'
      shell: cmd
      working-directory: ${{github.workspace}}/build/${{env.GITHUB_REPOSITORY_NAME}}/${{matrix.configuration}}
      run: ctest -C ${{matrix.configuration}} --output-on-failure

    - name: Analyze
      shell: cmd
      working-directory: ${{github.workspace}}/build/${{env.GITHUB_REPOSITORY_NAME}}/${{matrix.configuration}}
      run: cmake --build . --target clang-tidy

    - name: Save logs
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: |
          ${{github.workspace}}/build/${{env.GITHUB_REPOSITORY_NAME}}/${{matrix.configuration}}/*.log
          !${{github.workspace}}/build/${{env.GITHUB_REPOSITORY_NAME}}/${{matrix.configuration}}/clang-tidy.log
          ${{github.workspace}}/build/${{env.GITHUB_REPOSITORY_NAME}}/${{matrix.configuration}}/Testing/**/*.log
          ${{github.workspace}}/build/${{env.GITHUB_REPOSITORY_NAME}}/vcpkg-buildtrees/*/*.log

    - name: Save analysis
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: clang-tidy
        path: |
          ${{github.workspace}}/build/${{env.GITHUB_REPOSITORY_NAME}}/${{matrix.configuration}}/clang-tidy-*.log
          ${{github.workspace}}/build/${{env.GITHUB_REPOSITORY_NAME}}/${{matrix.configuration}}/clang-tidy-*.log
