name: build

on:
  push:
    branches: [ master, 'feature**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [ Debug, Release ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create Build Directory
      run: cmake -E make_directory ${{github.workspace}}/build/project/${{ matrix.configuration }}

    - name: Configure
      working-directory: ${{github.workspace}}/build/project/${{ matrix.configuration }}
      run: cmake -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DBUILD_ROOT=${{github.workspace}}/build -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/toolchain.cmake -G Ninja ${{github.workspace}}

    - name: Test
      working-directory: ${{github.workspace}}/build/project/${{ matrix.configuration }}
      run: ctest -C ${{ matrix.configuration }}
