name: Check

on:
  push:

concurrency:
  group: run-codeql-${{github.workflow}}-${{github.event_name}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  analyze:
    name: Analyze
    runs-on: windows-latest

    steps:
    - shell: bash
      run: |
        echo "- qlpack: codeql/cpp-queries" > test.qls
        echo "- include:" >> test.qls
        echo "  id:" >> test.qls
        echo "  - cpp/fixme-comment" >> test.qls

    # CodeQL: Setup
    - name: 'CodeQL: Initialize'
      uses: github/codeql-action/init@v2
      with:
        languages: cpp
        queries: ./test.qls
