name: Test

on:
  push:
    branches: [ master, 'feature**' ]
    paths:
      - '.github/workflows/**'
      - '!.github/workflows/run-**'
      - 'configure/**'
      - 'modules/**'
      - 'scripts/**'
      - 'test/**'
      - 'Toolchain.cmake'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/**'
      - '!.github/workflows/run-**'
      - 'configure/**'
      - 'modules/**'
      - 'scripts/**'
      - 'test/**'
      - 'Toolchain.cmake'

jobs:
  build:
    name: Test
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [ Debug, Release ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache vcpkg
      uses: actions/cache@v2
      with:
        path: build/${{matrix.configuration}}/vcpkg_installed
        key: vcpkg_installed-${{matrix.configuration}}-${{hashFiles('**/vcpkg.json', '**/vcpkg-configuration.json', '!build/**')}}

    - name: Setup MSVC Environment
      uses: mbeckh/msvc-dev-cmd@v1

    - name: Configure
      uses: ./configure
      with:
        source-dir: test
        build-root: build
        binary-dir: build/${{matrix.configuration}}
        configuration: ${{matrix.configuration}}
        
    - name: Build
      shell: cmd
      working-directory: build/${{matrix.configuration}}
      run: cmake --build .

    - name: Test
      shell: cmd
      working-directory: build/${{matrix.configuration}}
      run: ctest --output-on-failure

    - name: Save Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.configuration}}-Logs
        path: |
          build/**/vcpkg-buildtrees/*/*.log
          !build/**/vcpkg-buildtrees/detect_compiler
          build/${{matrix.configuration}}/Testing/**/*.log
          build/${{matrix.configuration}}/clang-tidy-*.log
