name: Test

on:
  push:
    branches: [ master, 'feature**' ]
  pull_request:
    branches: [ master ]

permissions: {}

concurrency: 
  group: ${{github.workflow}}-${{github.event_name}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: windows-latest
    strategy:
      matrix:
        preset: [ '', 'x64']
        multi-config: [ '', 'multi' ]
        configuration: [ Debug, Release ]
        unity: [ '', 'unity' ]
      fail-fast: false
    permissions:
      actions: write
      contents: read
      packages: write
    
    steps:
    - name: Get Image Version
      id: image
      shell: cmd
      run: ((echo os=%ImageOs%) & (echo version=%ImageVersion%)) >> %GITHUB_OUTPUT%
      
    - name: Restore Common vcpkg Tools
      id: vcpkg-tools-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          vcpkg-downloads/tools/powershell-core-*
        key: cmu-vcpkg_tools-${{steps.image.outputs.os}}-${{steps.image.outputs.version}}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup MSVC Environment
      uses: ./msvc-dev-env

    - name: Configure
      uses: ./configure
      with:
        preset: ${{matrix.preset}}
        build-root: build
        source-dir: test
        binary-dir: build/cmake-utils
        generator: ${{matrix.multi-config && 'Ninja Multi-Config' || 'Ninja'}}
        configuration: ${{!matrix.multi-config && matrix.configuration || ''}}
        configurations: ${{matrix.multi-config && 'Debug;Release' || ''}}
        extra-args: ${{matrix.unity && '-D "CMAKE_UNITY_BUILD:BOOL=ON" -D "CMAKE_DISABLE_PRECOMPILE_HEADERS:BOOL=ON"' || ''}}
        
    - name: Check Caching of Common vcpkg Tools
      id: vcpkg-tools-check
      if: ${{always() && steps.vcpkg-tools-restore.outputs.cache-hit != 'true'}}
      shell: bash
      run:
        find vcpkg-downloads/tools -maxdepth 1 -type d -name 'powershell-core-*' -printf "found=1\n" -quit >> $GITHUB_OUTPUT

    - name: Cache Common vcpkg Tools
      if: ${{always() && steps.vcpkg-tools-restore.outputs.cache-hit != 'true' && steps.vcpkg-tools-check.outputs.found == '1'}}
      uses: actions/cache/save@v3
      with:
        path: |
          vcpkg-downloads/tools/powershell-core-*
        key: ${{steps.vcpkg-tools-restore.outputs.cache-primary-key}}
        
    - name: Build
      shell: cmd
      working-directory: build/cmake-utils
      run: cmake --build . ${{matrix.multi-config && format('--config "{0}"', matrix.configuration) || ''}}

    - name: Test
      shell: cmd
      working-directory: build/cmake-utils
      run: ctest --output-on-failure ${{matrix.multi-config && format('-C "{0}"', matrix.configuration) || ''}}

    - name: Save Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Build-${{matrix.preset || 'nopreset'}}-${{matrix.multi-config || 'single'}}-${{matrix.configuration}}-${{matrix.unity || 'regular'}}-Logs
        path: |
          build/cmake-utils/vcpkg-buildtrees/*/*.log
          !build/cmake-utils/vcpkg-buildtrees/detect_compiler
          build/cmake-utils/Testing/**/*.log
          build/cmake-utils/**/clang-tidy-*.log
        if-no-files-found: ignore

  build-workflow:
    name: Build Workflow
    uses: ./.github/workflows/run-build.yml
    with:
      source-dir: test
      test-args: --label-regex "^Run$"
      pch: false
    secrets: inherit
    permissions:
      actions: write
      contents: read
      packages: write

  codeql-workflow:
    name: CodeQL Workflow
    uses: ./.github/workflows/run-codeql.yml
    with:
      source-dir: test
    secrets: inherit
    permissions:
      actions: write
      contents: read
      packages: write
      security-events: write

