name: Test

on:
  push:
    branches: [ master, 'feature**', 'multiconfig' ]
  pull_request:
    branches: [ master ]

concurrency: 
  group: ${{github.workflow}}-${{github.event_name}}-${{github.head_ref || github.ref}}
  cancel-in-progress: true

jobs:
  build:
    name: Test
    runs-on: windows-latest
    strategy:
      matrix:
        preset: [ '', 'x64']
        generator: [ Ninja, 'Ninja Multi-Config']
        configuration: [ Debug, Release ]
        unity: [ false, true ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache vcpkg
      uses: actions/cache@v2
      with:
        path: build/vcpkg_installed
        key: vcpkg_installed-${{matrix.preset || 'nopreset'}}-${{matrix.generator}}-${{matrix.configuration}}-${{matrix.unity && 'unity' || 'regular'}}-${{hashFiles('**/vcpkg.json', '**/vcpkg-configuration.json', '!build/**')}}

    - name: Setup MSVC Environment
      uses: mbeckh/msvc-dev-cmd@v1

    - name: Configure
      uses: ./configure
      with:
        preset: ${{matrix.preset}}
        build-root: build
        source-dir: test
        binary-dir: build/cmake-utils
        generator: ${{matrix.generator}}
        configuration: ${{matrix.generator == 'Ninja' && matrix.configuration || ''}}
        configurations: ${{matrix.generator == 'Ninja Multi-Config' && 'Debug;Release' || ''}}
        extra-args: ${{matrix.unity && '-D CMAKE_UNITY_BUILD:BOOL=ON -D CMAKE_DISABLE_PRECOMPILE_HEADERS:BOOL=ON' || ''}}
        
    - name: Build
      shell: cmd
      working-directory: build/cmake-utils
      run: cmake --build . ${{matrix.generator == 'Ninja Multi-Config' && format('--config "{0}"', matrix.configuration) || ''}}

    - name: Test
      shell: cmd
      working-directory: build/cmake-utils
      run: ctest --output-on-failure ${{matrix.generator == 'Ninja Multi-Config' && format('-C "{0}"', matrix.configuration) || ''}}

    - name: Save Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ${matrix.preset || 'nopreset'}}-${{matrix.generator}}-${{matrix.configuration}}-${{matrix.unity && 'unity' || 'regular'}}-Logs
        path: |
          build/vcpkg-buildtrees/*/*.log
          !build/vcpkg-buildtrees/detect_compiler
          build/cmake-utils/Testing/**/*.log
          build/cmake-utils/**/clang-tidy-*.log
