name: Test

on:
  push:
    branches: [ master, 'feature**' ]
  pull_request:
    branches: [ master ]

permissions: {}

concurrency: 
  group: ${{github.workflow}}-${{github.event_name}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  warm-up:
    name: Warm-up Caches
    outputs:
      tools-cache-key: ${{steps.tools-restore.outputs.cache-primary-key}}
      vcpkg-registries-cache-key: ${{steps.vcpkg-registries-restore.outputs.cache-primary-key}}
      vcpkg-cache-key: ${{steps.vcpkg-restore.outputs.cache-primary-key}}
    runs-on: windows-latest
    permissions:
      actions: write
      contents: read
      packages: write

    steps:
    # Actions: Load
    - name: 'Actions: Restore'
      id: actions-restore
      uses: actions/cache/restore@v3
      with:
        path: cmake-utils
        key: cmu-cmake-utils-${{github.workflow_sha}}

    - name: 'Actions: Load'
      if: ${{steps.actions-restore.outputs.cache-hit != 'true'}}
      shell: bash
      env:
        GITHUB_TOKEN: ${{github.token}}
      run: |
        curl -L --no-progress-meter -o "cmake-utils-$GITHUB_WORKFLOW_SHA.tar.gz" \
             -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" \
             "$GITHUB_API_URL/repos/mbeckh/cmake-utils/tarball/$GITHUB_WORKFLOW_SHA"
        mkdir cmake-utils
        tar -x $([[ $RUNNER_DEBUG == 1 ]] && echo -- "-v") -f "cmake-utils-$GITHUB_WORKFLOW_SHA.tar.gz" -C cmake-utils \
            --strip-components=1 --show-transformed-names --exclude='*.md' --wildcards \
            '*/configure' '*/modules' '*/msvc-dev-env' '*/Toolchain.cmake' \

    - name: 'Actions: Cache'
      if: ${{steps.actions-restore.outputs.cache-hit != 'true'}}
      uses: actions/cache/save@v3
      with:
        path: cmake-utils
        key: ${{steps.actions-restore.outputs.cache-primary-key}}

    # Source: Load
    - name: 'Source: Restore'
      id: source-restore
      uses: actions/cache/restore@v3
      with:
        path: source
        key: cmu-source-${{github.sha}}
        restore-keys: cmu-source-

    - name: 'Source: Checkout'
      if: ${{steps.source-restore.outputs.cache-hit != 'true'}}
      uses: actions/checkout@v3
      with:
        path: source
        persist-credentials: false

    - name: 'Source: Remove Cache'
      if: ${{steps.source-restore.outputs.cache-hit != 'true' && steps.source-restore.outputs.cache-matched-key != ''}}
      shell: bash
      env:
        SOURCE_CACHE_KEY: ${{steps.source-restore.outputs.cache-matched-key}}
        GITHUB_TOKEN: ${{github.token}}
      run: |
        curl --get -X DELETE --no-progress-meter \
             -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" \
             --data-urlencode "key=$SOURCE_CACHE_KEY" --data-urlencode "ref=$GITHUB_REF" \
             "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/caches"

    - name: 'Source: Cache'
      if: ${{steps.source-restore.outputs.cache-hit != 'true'}}
      uses: actions/cache/save@v3
      with:
        path: source
        key: ${{steps.source-restore.outputs.cache-primary-key}}

    # Build Environment: Load
    - name: 'vcpkg: Hashes'
      id: state
      shell: bash
      working-directory: source/test
      run: |
        ((echo "image-os=$ImageOS") & (echo "image-version=$ImageVersion")) >> $GITHUB_OUTPUT
        if [[ -f vcpkg.json ]]; then
          registries=$(jq --sort-keys $([[ -f vcpkg-configuration.json ]] && echo '--slurp') '.' \
                           vcpkg.json $([[ -f vcpkg-configuration.json ]] && echo 'vcpkg-configuration.json') \
            | tee >((echo -n 'manifest-hash=' && (sha1sum - | cut -d ' ' -f 1)) >> $GITHUB_OUTPUT) \
            | jq '
                [
                  .. | ((."default-registry"? | objects), (.registries? | .[]?))
                  | select(.kind == "git")
                  | { repository, reference, baseline }
                  | del(.. | nulls)  
                ] | sort')
          [[ $RUNNER_DEBUG -eq 1 ]] && echo "$registries" || true
          if [[ $registries != '[]' ]]; then
            (echo -n 'registries-hash=' && (sha1sum - | cut -d ' ' -f 1)) >> $GITHUB_OUTPUT
          fi
        fi

    - name: 'Tools: Restore'
      id: tools-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          cmake-utils/.msvc.env
          vcpkg-downloads/tools/powershell-core-*
        key: cmu-tools-${{steps.state.outputs.image-os}}-${{steps.state.outputs.image-version}}

    - name: 'vcpkg Registries: Restore'
      id: vcpkg-registries-restore
      if: ${{steps.state.outputs.registries-hash != ''}}
      uses: actions/cache/restore@v3
      with:
        path: vcpkg-registries
        key: cmu-vcpkg-registries-${{steps.state.outputs.registries-hash}}
        restore-keys: cmu-vcpkg-registries-

    - name: 'vcpkg Packages: Restore'
      id: vcpkg-restore
      if: ${{steps.state.outputs.manifest-hash != ''}}
      uses: actions/cache/restore@v3
      with:
        path: build/vcpkg_installed
        key: cmu-vcpkg_installed-${{steps.state.outputs.manifest-hash}}
        restore-keys: cmu-vcpkg_installed-

    - name: 'MSVC Environment: Restore'
      id: tools-state
      shell: bash
      run: |
        echo "vcpkg-hash=${{hashFiles('build/vcpkg_installed/vcpkg/vcpkg-lock.json', 'build/vcpkg_installed/*/share/*/vcpkg_abi_info.txt')}}" >> $GITHUB_OUTPUT
        > cmake-utils/.stamp
        if [[ -f cmake-utils/.msvc.env ]]; then
          cat cmake-utils/.msvc.env >> $GITHUB_ENV 
          echo "msvc-restored=true" >> $GITHUB_OUTPUT
        fi

    - name: 'MSVC Environment: Setup'
      id: msvc-setup
      if: ${{steps.tools-state.outputs.msvc-restored != 'true'}}
      uses: ./cmake-utils/msvc-dev-env
      with:
        env-file: cmake-utils/.msvc.env

    # Install vcpkg
    - name: 'vcpkg: Install'
      id: configure
      shell: cmd
      env:
        GITHUB_TOKEN: ${{github.token}}
      run: |
        nuget sources Add -Name "GitHub" -Source "https://nuget.pkg.github.com/%GITHUB_REPOSITORY_OWNER%/index.json" -UserName "%GITHUB_REPOSITORY_OWNER%" -Password "%GITHUB_TOKEN%" -StorePasswordInClearText -NonInteractive
        nuget setapikey "%GITHUB_TOKEN%" -Source "https://nuget.pkg.github.com/%GITHUB_REPOSITORY_OWNER%/index.json" -NonInteractive
        set BUILD_ROOT=%GITHUB_WORKSPACE%
        set VCPKG_BINARY_SOURCES=clear;nuget,GitHub,readwrite
        if not exist %BUILD_ROOT%\vcpkg-registries md %BUILD_ROOT%\vcpkg-registries
        %VCPKG_INSTALLATION_ROOT%\vcpkg.exe install ^
          --debug --debug-env ^
          --vcpkg-root=%VCPKG_INSTALLATION_ROOT% --x-wait-for-lock --feature-flags=-compilertracking ^
          --triplet=x64-windows-static --host-triplet=x64-windows-static --overlay-triplets=%GITHUB_WORKSPACE%\cmake-utils\modules\triplets ^
          --downloads-root=%BUILD_ROOT%\vcpkg-downloads --x-registries-cache=%BUILD_ROOT%\vcpkg-registries ^
          --x-manifest-root=%GITHUB_WORKSPACE%\source\test --x-install-root=%BUILD_ROOT%\build\vcpkg_installed ^
          --x-buildtrees-root=%BUILD_ROOT%\build\vcpkg-buildtrees --x-packages-root=%BUILD_ROOT%\build\vcpkg-packages

    # Build Environment: Cache
    - name: 'Tools: Check for Updates'
      id: tools-check
      if: ${{always() && steps.configure.outcome != 'skipped' && steps.tools-restore.outputs.cache-matched-key != ''}}
      shell: bash
      env:
        TOOLS_CACHE_KEY: ${{steps.tools-restore.outputs.cache-matched-key}}
        GITHUB_TOKEN: ${{github.token}}
      run: |
        if [[ cmake-utils/.msvc.env -nt cmake-utils/.stamp \
              || -d vcpkg-downloads/tools \
                 && $(find vcpkg-downloads/tools -maxdepth 1 -type d -name 'powershell-core-*' -newer cmake-utils/.stamp -printf "1" -quit) == 1 ]]; then
          curl --get -X DELETE --no-progress-meter \
               -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" \
               --data-urlencode "key=$TOOLS_CACHE_KEY" --data-urlencode "ref=$GITHUB_REF" \
               "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/caches"
          echo "updated=true" >> $GITHUB_OUTPUT
        fi

    - name: 'Tools: Cache'
      if: ${{always() && steps.configure.outcome != 'skipped' && (steps.tools-restore.outputs.cache-hit != 'true' || steps.tools-check.outputs.updated == 'true')}}
      uses: actions/cache/save@v3
      with:
        path: |
          cmake-utils/.msvc.env
          vcpkg-downloads/tools/powershell-core-*
        key: ${{steps.tools-restore.outputs.cache-primary-key}}

    - name: 'vcpkg Registries: Check for Updates'
      id: vcpkg-registries-check
      if: ${{always() && steps.configure.outcome != 'skipped' && steps.vcpkg-registries-restore.outputs.cache-hit == 'true'}}
      shell: bash
      env:
        VCPKG_REGISTRIES_CACHE_KEY: ${{steps.vcpkg-registries-restore.outputs.cache-primary-key}}
        GITHUB_TOKEN: ${{github.token}}
      run: |
        if [[ $(find vcpkg-registries -type f -newer cmake-utils/.stamp -printf '1' -quit) == 1 ]]; then
          curl --get -X DELETE --no-progress-meter \
               -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" \
               --data-urlencode "key=$VCPKG_REGISTRIES_CACHE_KEY" --data-urlencode "ref=$GITHUB_REF" \
               "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/caches"
          echo "updated=true" >> $GITHUB_OUTPUT
        fi

    - name: 'vcpkg Registries: Cache'
      if: ${{always() && steps.configure.outcome != 'skipped' && steps.vcpkg-registries-restore.outcome != 'skipped' && (steps.vcpkg-registries-restore.outputs.cache-hit != 'true' || steps.vcpkg-registries-check.outputs.updated == 'true')}}
      uses: actions/cache/save@v3
      with:
        path: vcpkg-registries
        key: ${{steps.vcpkg-registries-restore.outputs.cache-primary-key}}

    - name: 'vcpkg Packages: Check for Updates'
      id: vcpkg-check
      if: ${{always() && steps.configure.outcome != 'skipped' && steps.vcpkg-restore.outputs.cache-hit == 'true' && steps.tools-state.outputs.vcpkg-hash != hashFiles('build/vcpkg_installed/vcpkg/vcpkg-lock.json', 'build/vcpkg_installed/*/share/*/vcpkg_abi_info.txt')}}
      shell: bash
      env:
        VCPKG_CACHE_KEY: ${{steps.vcpkg-restore.outputs.cache-primary-key}}
        GITHUB_TOKEN: ${{github.token}}
      run: |
        echo "### Updated vcpkg Dependencies" >> $GITHUB_STEP_SUMMARY
        find build/vcpkg_installed -newer cmake-utils/.stamp -printf '%P\n' >> $GITHUB_STEP_SUMMARY
        curl --get -X DELETE --no-progress-meter \
             -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" \
             --data-urlencode "key=$VCPKG_CACHE_KEY" --data-urlencode "ref=$GITHUB_REF" \
             "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/caches"

    - name: 'vcpkg Packages: Cache'
      if: ${{always() && steps.configure.outcome != 'skipped' && steps.vcpkg-restore.outcome != 'skipped' && (steps.vcpkg-restore.outputs.cache-hit != 'true' || steps.vcpkg-check.outcome == 'success')}}
      uses: actions/cache/save@v3
      with:
        path: build/vcpkg_installed
        key: ${{steps.vcpkg-restore.outputs.cache-primary-key}}

    # Logs
    - name: Save vcpkg Logs
      if: ${{always() && steps.configure.outcome != 'skipped'}}
      uses: actions/upload-artifact@v3
      with:
        name: Test-vcpkg-Logs
        path: |
          build/vcpkg-buildtrees/*/*.log
          !build/vcpkg-buildtrees/detect_compiler/**
        if-no-files-found: ignore

  test:
    name: Test
    needs: warm-up
    runs-on: windows-latest
    strategy:
      matrix:
        #preset: [ '', 'x64']
        #multi-config: [ '', 'multi' ]
        #configuration: [ Debug, Release ]
        configuration: Debug
        #unity: [ '', 'unity' ]
      fail-fast: false
    permissions:
      actions: read
      contents: read
      packages: write

    steps:
    # Restore
    - name: 'Actions: Restore'
      uses: actions/cache/restore@v3
      with:
        path: cmake-utils
        key: cmu-cmake-utils-${{github.workflow_sha}}
        fail-on-cache-miss: true

    - name: 'Source: Restore'
      uses: actions/cache/restore@v3
      with:
        path: source
        key: cmu-source-${{github.sha}}
        fail-on-cache-miss: true

    - name: 'Tools: Restore'
      uses: actions/cache/restore@v3
      with:
        path: |
          cmake-utils/.msvc.env
          vcpkg-downloads/tools/powershell-core-*
        key: ${{needs.warm-up.outputs.tools-cache-key}}
        fail-on-cache-miss: true

    - name: 'vcpkg Registries: Restore'
      if: ${{needs.warm-up.outputs.vcpkg-registries-cache-key != ''}}
      uses: actions/cache/restore@v3
      with:
        path: vcpkg-registries
        key: ${{needs.warm-up.outputs.vcpkg-registries-cache-key}}
        fail-on-cache-miss: true

    - name: 'vcpkg Packages: Restore'
      if: ${{needs.warm-up.outputs.vcpkg-cache-key != ''}}
      uses: actions/cache/restore@v3
      with:
        path: build/vcpkg_installed
        key: ${{needs.warm-up.outputs.vcpkg-cache-key}}
        fail-on-cache-miss: true

    - name: 'MSVC Environment: Restore'
      shell: bash
      run: cat cmake-utils/.msvc.env >> $GITHUB_ENV

    # Configure, Build and Test
    - name: Configure
      id: configure
      uses: ./cmake-utils/configure
      with:
        preset: ${{matrix.preset}}
        source-dir: source/test
        binary-dir: build
        generator: ${{matrix.multi-config && 'Ninja Multi-Config' || 'Ninja'}}
        configuration: ${{!matrix.multi-config && matrix.configuration || ''}}
        configurations: ${{matrix.multi-config && 'Debug;Release' || ''}}
        extra-args: ${{matrix.unity && '-D "CMAKE_UNITY_BUILD:BOOL=ON" -D "CMAKE_DISABLE_PRECOMPILE_HEADERS:BOOL=ON"' || ''}} -D "VCPKG_INSTALL_OPTIONS=--debug;--debug-env"
    - run: exit 1
    - name: Build
      shell: cmd
      working-directory: build
      run: cmake --build . ${{matrix.multi-config && format('--config "{0}"', matrix.configuration) || ''}}

    - name: Test
      shell: cmd
      working-directory: build
      run: ctest --output-on-failure ${{matrix.multi-config && format('-C "{0}"', matrix.configuration) || ''}}

    # Logs
    - name: Save Logs
      if: ${{always() && steps.configure.outcome != 'skipped'}}
      uses: actions/upload-artifact@v3
      with:
        name: Test-Build-${{matrix.preset || 'nopreset'}}-${{matrix.multi-config || 'single'}}-${{matrix.configuration}}-${{matrix.unity || 'regular'}}-Logs
        path: |
          build/vcpkg-buildtrees/*/*.log
          !build/vcpkg-buildtrees/detect_compiler
          build/Testing/**/*.log
          build/**/clang-tidy-*.log
        if-no-files-found: ignore

  build-workflow:
    name: Build Workflow
    if: 1 == 2
    needs: warm-up
    uses: ./.github/workflows/run-build.yml
    with:
      source-dir: test
      pch: false
      test-args: --label-regex "^Run$"
    secrets: inherit
    permissions:
      actions: write
      contents: read
      packages: write

  codeql-workflow:
    name: CodeQL Workflow
    if: 1 == 2
    needs: warm-up
    uses: ./.github/workflows/run-codeql.yml
    with:
      source-dir: test
      codeql-queries: fixme-comment
    secrets: inherit
    permissions:
      actions: write
      contents: read
      packages: write
      security-events: write
