name: Trial

on:
  push:
    branches: [ test ]
    
concurrency:
  group: Trial
  cancel-in-progress: true

jobs:
  job1:
    runs-on: windows-latest
    steps:
    - run: exit 1

  build-workflow:
    name: Build Workflow
    needs: job1
    uses: ./.github/workflows/run-build.yml
    with:
      source-dir: test
      test-args: --label-regex "^Run$"
      pch: false
    secrets: inherit
    permissions:
      actions: write
      contents: read
      packages: write
